# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: 
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: 9fa8bafd-af57-4843-a6c3-ad75a640f111
        run: heroku container:login 
      - name: Build and push
        env:
          HEROKU_API_KEY: 9fa8bafd-af57-4843-a6c3-ad75a640f111
        run: heroku container:push -a mp-violencia-domestica web 
      - name: Release
        env:
          HEROKU_API_KEY: 9fa8bafd-af57-4843-a6c3-ad75a640f111
        run: heroku container:release -a mp-violencia-domestica web 
